// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/trp/onboarding/OMS/proto/OrderService.proto

package protoGenerated;

import com.google.protobuf.InvalidProtocolBufferException;

import java.io.IOException;

/**
 * Protobuf type {@code protoGenerated.AcknowledgeReceipt}
 */
public final class AcknowledgeReceipt extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:protoGenerated.AcknowledgeReceipt)
        AcknowledgeReceiptOrBuilder {
    /**
     * The constant MESSAGE_FIELD_NUMBER.
     */
    public static final int MESSAGE_FIELD_NUMBER = 1;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:protoGenerated.AcknowledgeReceipt)
    private static final protoGenerated.AcknowledgeReceipt DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<AcknowledgeReceipt>
            PARSER = new com.google.protobuf.AbstractParser<AcknowledgeReceipt>() {
        @java.lang.Override
        public AcknowledgeReceipt parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new AcknowledgeReceipt(input, extensionRegistry);
        }
    };

    static {
        DEFAULT_INSTANCE = new protoGenerated.AcknowledgeReceipt();
    }

    private volatile java.lang.Object message_;
    private byte memoizedIsInitialized = -1;

    // Use AcknowledgeReceipt.newBuilder() to construct.
    private AcknowledgeReceipt(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private AcknowledgeReceipt() {
        message_ = "";
    }

    private AcknowledgeReceipt(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 10: {
                        java.lang.String s = input.readStringRequireUtf8();

                        message_ = s;
                        break;
                    }
                    default: {
                        if (!parseUnknownField(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    /**
     * Gets descriptor.
     *
     * @return the descriptor
     */
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return protoGenerated.OrderServiceOuterClass.internal_static_protoGenerated_AcknowledgeReceipt_descriptor;
    }

    /**
     * Parse from proto generated . acknowledge receipt.
     *
     * @param data the data
     * @return the proto generated . acknowledge receipt
     * @throws InvalidProtocolBufferException the invalid protocol buffer exception
     */
    public static protoGenerated.AcknowledgeReceipt parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    /**
     * Parse from proto generated . acknowledge receipt.
     *
     * @param data              the data
     * @param extensionRegistry the extension registry
     * @return the proto generated . acknowledge receipt
     * @throws InvalidProtocolBufferException the invalid protocol buffer exception
     */
    public static protoGenerated.AcknowledgeReceipt parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    /**
     * Parse from proto generated . acknowledge receipt.
     *
     * @param data the data
     * @return the proto generated . acknowledge receipt
     * @throws InvalidProtocolBufferException the invalid protocol buffer exception
     */
    public static protoGenerated.AcknowledgeReceipt parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    /**
     * Parse from proto generated . acknowledge receipt.
     *
     * @param data              the data
     * @param extensionRegistry the extension registry
     * @return the proto generated . acknowledge receipt
     * @throws InvalidProtocolBufferException the invalid protocol buffer exception
     */
    public static protoGenerated.AcknowledgeReceipt parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    /**
     * Parse from proto generated . acknowledge receipt.
     *
     * @param data the data
     * @return the proto generated . acknowledge receipt
     * @throws InvalidProtocolBufferException the invalid protocol buffer exception
     */
    public static protoGenerated.AcknowledgeReceipt parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    /**
     * Parse from proto generated . acknowledge receipt.
     *
     * @param data              the data
     * @param extensionRegistry the extension registry
     * @return the proto generated . acknowledge receipt
     * @throws InvalidProtocolBufferException the invalid protocol buffer exception
     */
    public static protoGenerated.AcknowledgeReceipt parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    /**
     * Parse from proto generated . acknowledge receipt.
     *
     * @param input the input
     * @return the proto generated . acknowledge receipt
     * @throws IOException the io exception
     */
    public static protoGenerated.AcknowledgeReceipt parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    /**
     * Parse from proto generated . acknowledge receipt.
     *
     * @param input             the input
     * @param extensionRegistry the extension registry
     * @return the proto generated . acknowledge receipt
     * @throws IOException the io exception
     */
    public static protoGenerated.AcknowledgeReceipt parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    /**
     * Parse delimited from proto generated . acknowledge receipt.
     *
     * @param input the input
     * @return the proto generated . acknowledge receipt
     * @throws IOException the io exception
     */
    public static protoGenerated.AcknowledgeReceipt parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    /**
     * Parse delimited from proto generated . acknowledge receipt.
     *
     * @param input             the input
     * @param extensionRegistry the extension registry
     * @return the proto generated . acknowledge receipt
     * @throws IOException the io exception
     */
    public static protoGenerated.AcknowledgeReceipt parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    /**
     * Parse from proto generated . acknowledge receipt.
     *
     * @param input the input
     * @return the proto generated . acknowledge receipt
     * @throws IOException the io exception
     */
    public static protoGenerated.AcknowledgeReceipt parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    /**
     * Parse from proto generated . acknowledge receipt.
     *
     * @param input             the input
     * @param extensionRegistry the extension registry
     * @return the proto generated . acknowledge receipt
     * @throws IOException the io exception
     */
    public static protoGenerated.AcknowledgeReceipt parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    /**
     * New builder builder.
     *
     * @return the builder
     */
    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    /**
     * New builder builder.
     *
     * @param prototype the prototype
     * @return the builder
     */
    public static Builder newBuilder(protoGenerated.AcknowledgeReceipt prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Gets default instance.
     *
     * @return the default instance
     */
    public static protoGenerated.AcknowledgeReceipt getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    /**
     * Parser com . google . protobuf . parser.
     *
     * @return the com . google . protobuf . parser
     */
    public static com.google.protobuf.Parser<AcknowledgeReceipt> parser() {
        return PARSER;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
        return new AcknowledgeReceipt();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return protoGenerated.OrderServiceOuterClass.internal_static_protoGenerated_AcknowledgeReceipt_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        protoGenerated.AcknowledgeReceipt.class, protoGenerated.AcknowledgeReceipt.Builder.class);
    }

    /**
     * <code>string message = 1;</code>
     *
     * @return The message.
     */
    public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            message_ = s;
            return s;
        }
    }

    /**
     * <code>string message = 1;</code>
     *
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
    getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            message_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (!getMessageBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, message_);
        }
        unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getMessageBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, message_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof protoGenerated.AcknowledgeReceipt)) {
            return super.equals(obj);
        }
        protoGenerated.AcknowledgeReceipt other = (protoGenerated.AcknowledgeReceipt) obj;

        if (!getMessage()
                .equals(other.getMessage())) return false;
        return unknownFields.equals(other.unknownFields);
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getMessage().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AcknowledgeReceipt> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public protoGenerated.AcknowledgeReceipt getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    /**
     * Protobuf type {@code protoGenerated.AcknowledgeReceipt}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:protoGenerated.AcknowledgeReceipt)
            protoGenerated.AcknowledgeReceiptOrBuilder {
        private java.lang.Object message_ = "";

        // Construct using protoGenerated.AcknowledgeReceipt.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        /**
         * Gets descriptor.
         *
         * @return the descriptor
         */
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return protoGenerated.OrderServiceOuterClass.internal_static_protoGenerated_AcknowledgeReceipt_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return protoGenerated.OrderServiceOuterClass.internal_static_protoGenerated_AcknowledgeReceipt_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            protoGenerated.AcknowledgeReceipt.class, protoGenerated.AcknowledgeReceipt.Builder.class);
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            message_ = "";

            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return protoGenerated.OrderServiceOuterClass.internal_static_protoGenerated_AcknowledgeReceipt_descriptor;
        }

        @java.lang.Override
        public protoGenerated.AcknowledgeReceipt getDefaultInstanceForType() {
            return protoGenerated.AcknowledgeReceipt.getDefaultInstance();
        }

        @java.lang.Override
        public protoGenerated.AcknowledgeReceipt build() {
            protoGenerated.AcknowledgeReceipt result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public protoGenerated.AcknowledgeReceipt buildPartial() {
            protoGenerated.AcknowledgeReceipt result = new protoGenerated.AcknowledgeReceipt(this);
            result.message_ = message_;
            onBuilt();
            return result;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof protoGenerated.AcknowledgeReceipt) {
                return mergeFrom((protoGenerated.AcknowledgeReceipt) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        /**
         * Merge from builder.
         *
         * @param other the other
         * @return the builder
         */
        public Builder mergeFrom(protoGenerated.AcknowledgeReceipt other) {
            if (other == protoGenerated.AcknowledgeReceipt.getDefaultInstance()) return this;
            if (!other.getMessage().isEmpty()) {
                message_ = other.message_;
                onChanged();
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            protoGenerated.AcknowledgeReceipt parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (protoGenerated.AcknowledgeReceipt) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        /**
         * <code>string message = 1;</code>
         *
         * @return The message.
         */
        public java.lang.String getMessage() {
            java.lang.Object ref = message_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                message_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string message = 1;</code>
         *
         * @param value The message to set.
         * @return This builder for chaining.
         */
        public Builder setMessage(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            message_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string message = 1;</code>
         *
         * @return The bytes for message.
         */
        public com.google.protobuf.ByteString
        getMessageBytes() {
            java.lang.Object ref = message_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                message_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string message = 1;</code>
         *
         * @param value The bytes for message to set.
         * @return This builder for chaining.
         */
        public Builder setMessageBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            message_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string message = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearMessage() {

            message_ = getDefaultInstance().getMessage();
            onChanged();
            return this;
        }

        @java.lang.Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:protoGenerated.AcknowledgeReceipt)
    }

}

