// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/trp/onboarding/OMS/proto/OrderService.proto

package protoGenerated;

/**
 * The interface Acknowledge receipt or builder.
 */
public interface AcknowledgeReceiptOrBuilder extends
        // @@protoc_insertion_point(interface_extends:protoGenerated.AcknowledgeReceipt)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string message = 1;</code>
     *
     * @return The message.
     */
    java.lang.String getMessage();

    /**
     * <code>string message = 1;</code>
     *
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
    getMessageBytes();
}
