// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/trp/onboarding/OMS/proto/OrderService.proto

package protoGenerated;

/**
 * The interface Order or builder.
 */
public interface OrderOrBuilder extends
        // @@protoc_insertion_point(interface_extends:protoGenerated.Order)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     *
     * @return The id.
     */
    java.lang.String getId();

    /**
     * <code>string id = 1;</code>
     *
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
    getIdBytes();

    /**
     * <code>string userEmail = 2;</code>
     *
     * @return The userEmail.
     */
    java.lang.String getUserEmail();

    /**
     * <code>string userEmail = 2;</code>
     *
     * @return The bytes for userEmail.
     */
    com.google.protobuf.ByteString
    getUserEmailBytes();

    /**
     * <code>.google.protobuf.Timestamp orderTime = 3;</code>
     *
     * @return Whether the orderTime field is set.
     */
    boolean hasOrderTime();

    /**
     * <code>.google.protobuf.Timestamp orderTime = 3;</code>
     *
     * @return The orderTime.
     */
    com.google.protobuf.Timestamp getOrderTime();

    /**
     * <code>.google.protobuf.Timestamp orderTime = 3;</code>
     *
     * @return the order time or builder
     */
    com.google.protobuf.TimestampOrBuilder getOrderTimeOrBuilder();

    /**
     * <code>string ticker = 4;</code>
     *
     * @return The ticker.
     */
    java.lang.String getTicker();

    /**
     * <code>string ticker = 4;</code>
     *
     * @return The bytes for ticker.
     */
    com.google.protobuf.ByteString
    getTickerBytes();

    /**
     * <code>string direction = 5;</code>
     *
     * @return The direction.
     */
    java.lang.String getDirection();

    /**
     * <code>string direction = 5;</code>
     *
     * @return The bytes for direction.
     */
    com.google.protobuf.ByteString
    getDirectionBytes();

    /**
     * <code>double price = 6;</code>
     *
     * @return The price.
     */
    double getPrice();

    /**
     * <code>int32 quantity = 7;</code>
     *
     * @return The quantity.
     */
    int getQuantity();
}
