// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/trp/onboarding/OMS/proto/OrderService.proto

package protoGenerated;

import com.google.protobuf.InvalidProtocolBufferException;

import java.io.IOException;

/**
 * Protobuf type {@code protoGenerated.Order}
 */
public final class Order extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:protoGenerated.Order)
        OrderOrBuilder {
    /**
     * The constant ID_FIELD_NUMBER.
     */
    public static final int ID_FIELD_NUMBER = 1;
    /**
     * The constant USEREMAIL_FIELD_NUMBER.
     */
    public static final int USEREMAIL_FIELD_NUMBER = 2;
    /**
     * The constant ORDERTIME_FIELD_NUMBER.
     */
    public static final int ORDERTIME_FIELD_NUMBER = 3;
    /**
     * The constant TICKER_FIELD_NUMBER.
     */
    public static final int TICKER_FIELD_NUMBER = 4;
    /**
     * The constant DIRECTION_FIELD_NUMBER.
     */
    public static final int DIRECTION_FIELD_NUMBER = 5;
    /**
     * The constant PRICE_FIELD_NUMBER.
     */
    public static final int PRICE_FIELD_NUMBER = 6;
    /**
     * The constant QUANTITY_FIELD_NUMBER.
     */
    public static final int QUANTITY_FIELD_NUMBER = 7;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:protoGenerated.Order)
    private static final protoGenerated.Order DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<Order>
            PARSER = new com.google.protobuf.AbstractParser<Order>() {
        @java.lang.Override
        public Order parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new Order(input, extensionRegistry);
        }
    };

    static {
        DEFAULT_INSTANCE = new protoGenerated.Order();
    }

    private volatile java.lang.Object id_;
    private volatile java.lang.Object userEmail_;
    private com.google.protobuf.Timestamp orderTime_;
    private volatile java.lang.Object ticker_;
    private volatile java.lang.Object direction_;
    private double price_;
    private int quantity_;
    private byte memoizedIsInitialized = -1;

    // Use Order.newBuilder() to construct.
    private Order(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private Order() {
        id_ = "";
        userEmail_ = "";
        ticker_ = "";
        direction_ = "";
    }

    private Order(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 10: {
                        java.lang.String s = input.readStringRequireUtf8();

                        id_ = s;
                        break;
                    }
                    case 18: {
                        java.lang.String s = input.readStringRequireUtf8();

                        userEmail_ = s;
                        break;
                    }
                    case 26: {
                        com.google.protobuf.Timestamp.Builder subBuilder = null;
                        if (orderTime_ != null) {
                            subBuilder = orderTime_.toBuilder();
                        }
                        orderTime_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom(orderTime_);
                            orderTime_ = subBuilder.buildPartial();
                        }

                        break;
                    }
                    case 34: {
                        java.lang.String s = input.readStringRequireUtf8();

                        ticker_ = s;
                        break;
                    }
                    case 42: {
                        java.lang.String s = input.readStringRequireUtf8();

                        direction_ = s;
                        break;
                    }
                    case 49: {

                        price_ = input.readDouble();
                        break;
                    }
                    case 56: {

                        quantity_ = input.readInt32();
                        break;
                    }
                    default: {
                        if (!parseUnknownField(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    /**
     * Gets descriptor.
     *
     * @return the descriptor
     */
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return protoGenerated.OrderServiceOuterClass.internal_static_protoGenerated_Order_descriptor;
    }

    /**
     * Parse from proto generated . order.
     *
     * @param data the data
     * @return the proto generated . order
     * @throws InvalidProtocolBufferException the invalid protocol buffer exception
     */
    public static protoGenerated.Order parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    /**
     * Parse from proto generated . order.
     *
     * @param data              the data
     * @param extensionRegistry the extension registry
     * @return the proto generated . order
     * @throws InvalidProtocolBufferException the invalid protocol buffer exception
     */
    public static protoGenerated.Order parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    /**
     * Parse from proto generated . order.
     *
     * @param data the data
     * @return the proto generated . order
     * @throws InvalidProtocolBufferException the invalid protocol buffer exception
     */
    public static protoGenerated.Order parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    /**
     * Parse from proto generated . order.
     *
     * @param data              the data
     * @param extensionRegistry the extension registry
     * @return the proto generated . order
     * @throws InvalidProtocolBufferException the invalid protocol buffer exception
     */
    public static protoGenerated.Order parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    /**
     * Parse from proto generated . order.
     *
     * @param data the data
     * @return the proto generated . order
     * @throws InvalidProtocolBufferException the invalid protocol buffer exception
     */
    public static protoGenerated.Order parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    /**
     * Parse from proto generated . order.
     *
     * @param data              the data
     * @param extensionRegistry the extension registry
     * @return the proto generated . order
     * @throws InvalidProtocolBufferException the invalid protocol buffer exception
     */
    public static protoGenerated.Order parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    /**
     * Parse from proto generated . order.
     *
     * @param input the input
     * @return the proto generated . order
     * @throws IOException the io exception
     */
    public static protoGenerated.Order parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    /**
     * Parse from proto generated . order.
     *
     * @param input             the input
     * @param extensionRegistry the extension registry
     * @return the proto generated . order
     * @throws IOException the io exception
     */
    public static protoGenerated.Order parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    /**
     * Parse delimited from proto generated . order.
     *
     * @param input the input
     * @return the proto generated . order
     * @throws IOException the io exception
     */
    public static protoGenerated.Order parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    /**
     * Parse delimited from proto generated . order.
     *
     * @param input             the input
     * @param extensionRegistry the extension registry
     * @return the proto generated . order
     * @throws IOException the io exception
     */
    public static protoGenerated.Order parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    /**
     * Parse from proto generated . order.
     *
     * @param input the input
     * @return the proto generated . order
     * @throws IOException the io exception
     */
    public static protoGenerated.Order parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    /**
     * Parse from proto generated . order.
     *
     * @param input             the input
     * @param extensionRegistry the extension registry
     * @return the proto generated . order
     * @throws IOException the io exception
     */
    public static protoGenerated.Order parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    /**
     * New builder builder.
     *
     * @return the builder
     */
    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    /**
     * New builder builder.
     *
     * @param prototype the prototype
     * @return the builder
     */
    public static Builder newBuilder(protoGenerated.Order prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Gets default instance.
     *
     * @return the default instance
     */
    public static protoGenerated.Order getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    /**
     * Parser com . google . protobuf . parser.
     *
     * @return the com . google . protobuf . parser
     */
    public static com.google.protobuf.Parser<Order> parser() {
        return PARSER;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
        return new Order();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return protoGenerated.OrderServiceOuterClass.internal_static_protoGenerated_Order_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        protoGenerated.Order.class, protoGenerated.Order.Builder.class);
    }

    /**
     * <code>string id = 1;</code>
     *
     * @return The id.
     */
    public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            id_ = s;
            return s;
        }
    }

    /**
     * <code>string id = 1;</code>
     *
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
    getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            id_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>string userEmail = 2;</code>
     *
     * @return The userEmail.
     */
    public java.lang.String getUserEmail() {
        java.lang.Object ref = userEmail_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            userEmail_ = s;
            return s;
        }
    }

    /**
     * <code>string userEmail = 2;</code>
     *
     * @return The bytes for userEmail.
     */
    public com.google.protobuf.ByteString
    getUserEmailBytes() {
        java.lang.Object ref = userEmail_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            userEmail_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>.google.protobuf.Timestamp orderTime = 3;</code>
     *
     * @return Whether the orderTime field is set.
     */
    public boolean hasOrderTime() {
        return orderTime_ != null;
    }

    /**
     * <code>.google.protobuf.Timestamp orderTime = 3;</code>
     *
     * @return The orderTime.
     */
    public com.google.protobuf.Timestamp getOrderTime() {
        return orderTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : orderTime_;
    }

    /**
     * <code>.google.protobuf.Timestamp orderTime = 3;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getOrderTimeOrBuilder() {
        return getOrderTime();
    }

    /**
     * <code>string ticker = 4;</code>
     *
     * @return The ticker.
     */
    public java.lang.String getTicker() {
        java.lang.Object ref = ticker_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            ticker_ = s;
            return s;
        }
    }

    /**
     * <code>string ticker = 4;</code>
     *
     * @return The bytes for ticker.
     */
    public com.google.protobuf.ByteString
    getTickerBytes() {
        java.lang.Object ref = ticker_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            ticker_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>string direction = 5;</code>
     *
     * @return The direction.
     */
    public java.lang.String getDirection() {
        java.lang.Object ref = direction_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            direction_ = s;
            return s;
        }
    }

    /**
     * <code>string direction = 5;</code>
     *
     * @return The bytes for direction.
     */
    public com.google.protobuf.ByteString
    getDirectionBytes() {
        java.lang.Object ref = direction_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            direction_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>double price = 6;</code>
     *
     * @return The price.
     */
    public double getPrice() {
        return price_;
    }

    /**
     * <code>int32 quantity = 7;</code>
     *
     * @return The quantity.
     */
    public int getQuantity() {
        return quantity_;
    }

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (!getIdBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
        }
        if (!getUserEmailBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userEmail_);
        }
        if (orderTime_ != null) {
            output.writeMessage(3, getOrderTime());
        }
        if (!getTickerBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 4, ticker_);
        }
        if (!getDirectionBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 5, direction_);
        }
        if (price_ != 0D) {
            output.writeDouble(6, price_);
        }
        if (quantity_ != 0) {
            output.writeInt32(7, quantity_);
        }
        unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getIdBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
        }
        if (!getUserEmailBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userEmail_);
        }
        if (orderTime_ != null) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(3, getOrderTime());
        }
        if (!getTickerBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, ticker_);
        }
        if (!getDirectionBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, direction_);
        }
        if (price_ != 0D) {
            size += com.google.protobuf.CodedOutputStream
                    .computeDoubleSize(6, price_);
        }
        if (quantity_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(7, quantity_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof protoGenerated.Order)) {
            return super.equals(obj);
        }
        protoGenerated.Order other = (protoGenerated.Order) obj;

        if (!getId()
                .equals(other.getId())) return false;
        if (!getUserEmail()
                .equals(other.getUserEmail())) return false;
        if (hasOrderTime() != other.hasOrderTime()) return false;
        if (hasOrderTime()) {
            if (!getOrderTime()
                    .equals(other.getOrderTime())) return false;
        }
        if (!getTicker()
                .equals(other.getTicker())) return false;
        if (!getDirection()
                .equals(other.getDirection())) return false;
        if (java.lang.Double.doubleToLongBits(getPrice())
                != java.lang.Double.doubleToLongBits(
                other.getPrice())) return false;
        if (getQuantity()
                != other.getQuantity()) return false;
        return unknownFields.equals(other.unknownFields);
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
        hash = (37 * hash) + USEREMAIL_FIELD_NUMBER;
        hash = (53 * hash) + getUserEmail().hashCode();
        if (hasOrderTime()) {
            hash = (37 * hash) + ORDERTIME_FIELD_NUMBER;
            hash = (53 * hash) + getOrderTime().hashCode();
        }
        hash = (37 * hash) + TICKER_FIELD_NUMBER;
        hash = (53 * hash) + getTicker().hashCode();
        hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
        hash = (53 * hash) + getDirection().hashCode();
        hash = (37 * hash) + PRICE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                java.lang.Double.doubleToLongBits(getPrice()));
        hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
        hash = (53 * hash) + getQuantity();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Order> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public protoGenerated.Order getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    /**
     * Protobuf type {@code protoGenerated.Order}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:protoGenerated.Order)
            protoGenerated.OrderOrBuilder {
        private java.lang.Object id_ = "";
        private java.lang.Object userEmail_ = "";
        private com.google.protobuf.Timestamp orderTime_;
        private com.google.protobuf.SingleFieldBuilderV3<
                com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> orderTimeBuilder_;
        private java.lang.Object ticker_ = "";
        private java.lang.Object direction_ = "";
        private double price_;
        private int quantity_;

        // Construct using protoGenerated.Order.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        /**
         * Gets descriptor.
         *
         * @return the descriptor
         */
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return protoGenerated.OrderServiceOuterClass.internal_static_protoGenerated_Order_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return protoGenerated.OrderServiceOuterClass.internal_static_protoGenerated_Order_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            protoGenerated.Order.class, protoGenerated.Order.Builder.class);
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            id_ = "";

            userEmail_ = "";

            if (orderTimeBuilder_ == null) {
                orderTime_ = null;
            } else {
                orderTime_ = null;
                orderTimeBuilder_ = null;
            }
            ticker_ = "";

            direction_ = "";

            price_ = 0D;

            quantity_ = 0;

            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return protoGenerated.OrderServiceOuterClass.internal_static_protoGenerated_Order_descriptor;
        }

        @java.lang.Override
        public protoGenerated.Order getDefaultInstanceForType() {
            return protoGenerated.Order.getDefaultInstance();
        }

        @java.lang.Override
        public protoGenerated.Order build() {
            protoGenerated.Order result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public protoGenerated.Order buildPartial() {
            protoGenerated.Order result = new protoGenerated.Order(this);
            result.id_ = id_;
            result.userEmail_ = userEmail_;
            if (orderTimeBuilder_ == null) {
                result.orderTime_ = orderTime_;
            } else {
                result.orderTime_ = orderTimeBuilder_.build();
            }
            result.ticker_ = ticker_;
            result.direction_ = direction_;
            result.price_ = price_;
            result.quantity_ = quantity_;
            onBuilt();
            return result;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof protoGenerated.Order) {
                return mergeFrom((protoGenerated.Order) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        /**
         * Merge from builder.
         *
         * @param other the other
         * @return the builder
         */
        public Builder mergeFrom(protoGenerated.Order other) {
            if (other == protoGenerated.Order.getDefaultInstance()) return this;
            if (!other.getId().isEmpty()) {
                id_ = other.id_;
                onChanged();
            }
            if (!other.getUserEmail().isEmpty()) {
                userEmail_ = other.userEmail_;
                onChanged();
            }
            if (other.hasOrderTime()) {
                mergeOrderTime(other.getOrderTime());
            }
            if (!other.getTicker().isEmpty()) {
                ticker_ = other.ticker_;
                onChanged();
            }
            if (!other.getDirection().isEmpty()) {
                direction_ = other.direction_;
                onChanged();
            }
            if (other.getPrice() != 0D) {
                setPrice(other.getPrice());
            }
            if (other.getQuantity() != 0) {
                setQuantity(other.getQuantity());
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            protoGenerated.Order parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (protoGenerated.Order) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        /**
         * <code>string id = 1;</code>
         *
         * @return The id.
         */
        public java.lang.String getId() {
            java.lang.Object ref = id_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                id_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string id = 1;</code>
         *
         * @param value The id to set.
         * @return This builder for chaining.
         */
        public Builder setId(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            id_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string id = 1;</code>
         *
         * @return The bytes for id.
         */
        public com.google.protobuf.ByteString
        getIdBytes() {
            java.lang.Object ref = id_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                id_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string id = 1;</code>
         *
         * @param value The bytes for id to set.
         * @return This builder for chaining.
         */
        public Builder setIdBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            id_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string id = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearId() {

            id_ = getDefaultInstance().getId();
            onChanged();
            return this;
        }

        /**
         * <code>string userEmail = 2;</code>
         *
         * @return The userEmail.
         */
        public java.lang.String getUserEmail() {
            java.lang.Object ref = userEmail_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                userEmail_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string userEmail = 2;</code>
         *
         * @param value The userEmail to set.
         * @return This builder for chaining.
         */
        public Builder setUserEmail(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            userEmail_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string userEmail = 2;</code>
         *
         * @return The bytes for userEmail.
         */
        public com.google.protobuf.ByteString
        getUserEmailBytes() {
            java.lang.Object ref = userEmail_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                userEmail_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string userEmail = 2;</code>
         *
         * @param value The bytes for userEmail to set.
         * @return This builder for chaining.
         */
        public Builder setUserEmailBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            userEmail_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string userEmail = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearUserEmail() {

            userEmail_ = getDefaultInstance().getUserEmail();
            onChanged();
            return this;
        }

        /**
         * <code>.google.protobuf.Timestamp orderTime = 3;</code>
         *
         * @return Whether the orderTime field is set.
         */
        public boolean hasOrderTime() {
            return orderTimeBuilder_ != null || orderTime_ != null;
        }

        /**
         * <code>.google.protobuf.Timestamp orderTime = 3;</code>
         *
         * @return The orderTime.
         */
        public com.google.protobuf.Timestamp getOrderTime() {
            if (orderTimeBuilder_ == null) {
                return orderTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : orderTime_;
            } else {
                return orderTimeBuilder_.getMessage();
            }
        }

        /**
         * <code>.google.protobuf.Timestamp orderTime = 3;</code>
         *
         * @param value the value
         * @return the order time
         */
        public Builder setOrderTime(com.google.protobuf.Timestamp value) {
            if (orderTimeBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                orderTime_ = value;
                onChanged();
            } else {
                orderTimeBuilder_.setMessage(value);
            }

            return this;
        }

        /**
         * <code>.google.protobuf.Timestamp orderTime = 3;</code>
         *
         * @param builderForValue the builder for value
         * @return the order time
         */
        public Builder setOrderTime(
                com.google.protobuf.Timestamp.Builder builderForValue) {
            if (orderTimeBuilder_ == null) {
                orderTime_ = builderForValue.build();
                onChanged();
            } else {
                orderTimeBuilder_.setMessage(builderForValue.build());
            }

            return this;
        }

        /**
         * <code>.google.protobuf.Timestamp orderTime = 3;</code>
         *
         * @param value the value
         * @return the builder
         */
        public Builder mergeOrderTime(com.google.protobuf.Timestamp value) {
            if (orderTimeBuilder_ == null) {
                if (orderTime_ != null) {
                    orderTime_ =
                            com.google.protobuf.Timestamp.newBuilder(orderTime_).mergeFrom(value).buildPartial();
                } else {
                    orderTime_ = value;
                }
                onChanged();
            } else {
                orderTimeBuilder_.mergeFrom(value);
            }

            return this;
        }

        /**
         * <code>.google.protobuf.Timestamp orderTime = 3;</code>
         *
         * @return the builder
         */
        public Builder clearOrderTime() {
            if (orderTimeBuilder_ == null) {
                orderTime_ = null;
                onChanged();
            } else {
                orderTime_ = null;
                orderTimeBuilder_ = null;
            }

            return this;
        }

        /**
         * <code>.google.protobuf.Timestamp orderTime = 3;</code>
         *
         * @return the order time builder
         */
        public com.google.protobuf.Timestamp.Builder getOrderTimeBuilder() {

            onChanged();
            return getOrderTimeFieldBuilder().getBuilder();
        }

        /**
         * <code>.google.protobuf.Timestamp orderTime = 3;</code>
         */
        public com.google.protobuf.TimestampOrBuilder getOrderTimeOrBuilder() {
            if (orderTimeBuilder_ != null) {
                return orderTimeBuilder_.getMessageOrBuilder();
            } else {
                return orderTime_ == null ?
                        com.google.protobuf.Timestamp.getDefaultInstance() : orderTime_;
            }
        }

        /**
         * <code>.google.protobuf.Timestamp orderTime = 3;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>
        getOrderTimeFieldBuilder() {
            if (orderTimeBuilder_ == null) {
                orderTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                        getOrderTime(),
                        getParentForChildren(),
                        isClean());
                orderTime_ = null;
            }
            return orderTimeBuilder_;
        }

        /**
         * <code>string ticker = 4;</code>
         *
         * @return The ticker.
         */
        public java.lang.String getTicker() {
            java.lang.Object ref = ticker_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                ticker_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string ticker = 4;</code>
         *
         * @param value The ticker to set.
         * @return This builder for chaining.
         */
        public Builder setTicker(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            ticker_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string ticker = 4;</code>
         *
         * @return The bytes for ticker.
         */
        public com.google.protobuf.ByteString
        getTickerBytes() {
            java.lang.Object ref = ticker_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                ticker_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string ticker = 4;</code>
         *
         * @param value The bytes for ticker to set.
         * @return This builder for chaining.
         */
        public Builder setTickerBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            ticker_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string ticker = 4;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearTicker() {

            ticker_ = getDefaultInstance().getTicker();
            onChanged();
            return this;
        }

        /**
         * <code>string direction = 5;</code>
         *
         * @return The direction.
         */
        public java.lang.String getDirection() {
            java.lang.Object ref = direction_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                direction_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string direction = 5;</code>
         *
         * @param value The direction to set.
         * @return This builder for chaining.
         */
        public Builder setDirection(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            direction_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string direction = 5;</code>
         *
         * @return The bytes for direction.
         */
        public com.google.protobuf.ByteString
        getDirectionBytes() {
            java.lang.Object ref = direction_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                direction_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string direction = 5;</code>
         *
         * @param value The bytes for direction to set.
         * @return This builder for chaining.
         */
        public Builder setDirectionBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            direction_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string direction = 5;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearDirection() {

            direction_ = getDefaultInstance().getDirection();
            onChanged();
            return this;
        }

        /**
         * <code>double price = 6;</code>
         *
         * @return The price.
         */
        public double getPrice() {
            return price_;
        }

        /**
         * <code>double price = 6;</code>
         *
         * @param value The price to set.
         * @return This builder for chaining.
         */
        public Builder setPrice(double value) {

            price_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>double price = 6;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearPrice() {

            price_ = 0D;
            onChanged();
            return this;
        }

        /**
         * <code>int32 quantity = 7;</code>
         *
         * @return The quantity.
         */
        public int getQuantity() {
            return quantity_;
        }

        /**
         * <code>int32 quantity = 7;</code>
         *
         * @param value The quantity to set.
         * @return This builder for chaining.
         */
        public Builder setQuantity(int value) {

            quantity_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 quantity = 7;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearQuantity() {

            quantity_ = 0;
            onChanged();
            return this;
        }

        @java.lang.Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:protoGenerated.Order)
    }

}

