// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/trp/onboarding/OMS/proto/OrderService.proto

package protoGenerated;

/**
 * The type Order service outer class.
 */
public final class OrderServiceOuterClass {
    /**
     * The Internal static proto generated order descriptor.
     */
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_protoGenerated_Order_descriptor;
    /**
     * The Internal static proto generated order field accessor table.
     */
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_protoGenerated_Order_fieldAccessorTable;
    /**
     * The Internal static proto generated acknowledge receipt descriptor.
     */
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_protoGenerated_AcknowledgeReceipt_descriptor;
    /**
     * The Internal static proto generated acknowledge receipt field accessor table.
     */
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_protoGenerated_AcknowledgeReceipt_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n/com/trp/onboarding/OMS/proto/OrderServ" +
                        "ice.proto\022\016protoGenerated\032\037google/protob" +
                        "uf/timestamp.proto\"\231\001\n\005Order\022\n\n\002id\030\001 \001(\t" +
                        "\022\021\n\tuserEmail\030\002 \001(\t\022-\n\torderTime\030\003 \001(\0132\032" +
                        ".google.protobuf.Timestamp\022\016\n\006ticker\030\004 \001" +
                        "(\t\022\021\n\tdirection\030\005 \001(\t\022\r\n\005price\030\006 \001(\001\022\020\n\010" +
                        "quantity\030\007 \001(\005\"%\n\022AcknowledgeReceipt\022\017\n\007" +
                        "message\030\001 \001(\t2\233\001\n\014OrderService\022K\n\014execut" +
                        "eOrder\022\025.protoGenerated.Order\032\".protoGen" +
                        "erated.AcknowledgeReceipt\"\000\022>\n\014getOrderB" +
                        "yID\022\025.protoGenerated.Order\032\025.protoGenera" +
                        "ted.Order\"\000B\022\n\016protoGeneratedP\001b\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                com.google.protobuf.TimestampProto.getDescriptor(),
                        });
        internal_static_protoGenerated_Order_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_protoGenerated_Order_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_protoGenerated_Order_descriptor,
                new java.lang.String[]{"Id", "UserEmail", "OrderTime", "Ticker", "Direction", "Price", "Quantity",});
        internal_static_protoGenerated_AcknowledgeReceipt_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_protoGenerated_AcknowledgeReceipt_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_protoGenerated_AcknowledgeReceipt_descriptor,
                new java.lang.String[]{"Message",});
        com.google.protobuf.TimestampProto.getDescriptor();
    }

    private OrderServiceOuterClass() {
    }

    /**
     * Register all extensions.
     *
     * @param registry the registry
     */
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    /**
     * Register all extensions.
     *
     * @param registry the registry
     */
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    /**
     * Gets descriptor.
     *
     * @return the descriptor
     */
    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    // @@protoc_insertion_point(outer_class_scope)
}
